version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: ink-api
    env_file: .env
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres

  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ink_test
      PGDATA: /pgdata
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    volumes:
      - postgres-data:/pgdata

volumes:
  node_modules:
  postgres-data:
