name: Node CI

on: 
  workflow_dispatch:
    push: 
      branches: [dev]

jobs:
  install:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm install
      run: |
        npm install
      env:
        CI: true
  tests:
    runs-on: ubuntu-latest
    needs: [install]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_INSTANCE: localhost
          POSTGRES_DB: github-actiont-tests
        ports:
        - 5432:5432
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm lint
      run: |
        npm run lint
      env:
        CI: true 
    - name: npm test
      run: |
        npm run test
      env:
        CI: true
    
