name: Tests and Lint

on: 
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
      with: 
        ssh-key: ${{ secrets.SSH_KEY }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm install
      run: npm ci

  tests:
    runs-on: ubuntu-latest
    needs: [install]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_INSTANCE: localhost
          POSTGRES_DB: github-actiont-tests
        ports:
        - 5432:5432
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm lint
      run: npm run eslint ./
      env:
        CI: true 
    - name: npm test
      run: npm run test
      env:
        CI: true
    
