name: Tests and Lint

on: 
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v3
      with: 
        ssh-key: ${{ secrets.SSH_KEY }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm install
      run: npm ci

  tests:
    runs-on: ubuntu-latest
    needs: [install]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ink
          POSTGRES_INSTANCE: 127.0.0.1
          POSTGRES_DB: ink_test
          POSTGRES_PASSWORD: ink
          POSTGRES_PORT: 5432
        ports:
        - 5432:5432
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: install
      run: npm install
    - name: npm lint
      run: npm run lint
      env:
        CI: true 
    - name: npm test
      run: npm run test
      env:
        CI: true
        NODE_ENV: test
        POSTGRE_DB: ink_test
        POSTGRE_USER: ink
        POSTGRE_PASSWORD: ink
        POSTGRE_INSTANCE: 127.0.0.1
    
